import { Poppins } from "next/font/google";
import Navbar from "@/components/Navbar";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.variable}>
      <body>
        <Navbar />

        {children}

        {/* 👇 Footer Credit */}
        <footer className="site-credit">
          <p>
            © 2026 Dwellio •{" "}
            <a
              href="https://ahad.io"
              target="_blank"
              rel="noopener noreferrer"
            >
              Coded by Ahad.io
            </a>
          </p>
        </footer>
      </body>
    </html>
  );
}